name: Deploy

on:
  push:
    branches:
      - robert

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy Assets

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH and deploy to robert
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CPANEL_SERVER_IP }}
        username: ${{ secrets.CPANEL_USERNAME }}
        key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
        port: ${{ secrets.CPANEL_PORT }}
        script: |
          cd ~/zionvalley
          git branch
          composer install
