on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
		# Checkout the repository
		- name: 🚚 Get latest code
			uses: actions/checkout@v4

		- name: Install composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ftp.zionvalleycbo.org
        username: gitsample@zionvalleycbo.org
        password: T3stFtp@123456
