name: Deploy
on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Build & Deploy Assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.CPANEL_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.CPANEL_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh syncflux@${{ secrets.CPANEL_SERVER_IP }} 'bash -s' < ${{ github.workspace }}/.github/workflows/deploy.sh
