on:
  push:
    branches:
      - dev
name: Deploy website on push
jobs:
  FTP-Deploy-Action:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Install composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Sync files to staging
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
      	server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.STAGING_FTP_USER }}
        password: ${{ secrets.STAGING_FTP_PASS }}
