on:
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  FTP-Deploy-Action:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    # - name: Install composer Dependencies
    #   run: composer install --ignore-platform-reqs -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Sync files to production
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.PROD_FTP_USER }}
        password: ${{ secrets.PROD_FTP_PASS }}
