on:
  push:
    branches:
      - main
name: Deploy website on push
jobs:
  FTP-Deploy-Action:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
			# Checkout the repository
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.zionvalleycbo.org
        username: gitsample@zionvalleycbo.org
        password: T3stFtp@123456
