name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

		- name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ftp.zionvalleycbo.org
        username: gitsample@zionvalleycbo.org
        password: T3stFtp@123456
